os: linux
language: node_js

branches:
  only:
    - master
    - next

install: travis_retry npm install

jobs:
  include:
    - stage: test
      node_js:
        - node
        - lts/*
        - 10
      script:
        - npm test
        - npm run coveralls
    - stage: release
      if: type = push AND fork = false
      node_js: lts/*
      script:
        - npm run build:plugin
        - npx semantic-release
    - stage: deploy
      if: branch = master AND type = push AND fork = false
      node_js: lts/*
      script: npm run build:docs
      deploy:
        provider: pages
        local_dir: build
        token: $GH_TOKEN
        skip_cleanup: true
        on:
          tags: false
