os: linux
language: node_js

node_js:
  - node
  - lts/*
  - 10

install:
  - travis_retry npm install

script:
  - npm test
  - npm run coveralls

stages:
  - test
  - name: release
    if: branch = master

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run build
        - npm run build:docs
        - npx semantic-release
