os: linux
language: node_js

node_js:
  - node
  - lts/*
  - 10

branches:
  only:
    - master
    - next

install: travis_retry npm install

script:
  - npm test
  - npm run coveralls

before_deploy: npm run build

deploy:
  provider: pages
  local_dir: docs
  token: $GH_TOKEN
  skip_cleanup: true
  on:
    node_js: lts/*
    branch: master
    tags: false

jobs:
  include:
    - stage: release
      if: branch = master
      node_js: lts/*
      script: npx semantic-release
