os: linux
language: node_js

node_js:
  - node
  - lts/*
  - 10

branches:
  only:
    - master
    - next

install: travis_retry npm install

script:
  - npm test
  - npm run coveralls

jobs:
  include:
    - stage: release
      name: "Plugin"
      if: type = push AND fork = false
      node_js: lts/*
      script:
        - npm run build:plugin
        - npx semantic-release
    - stage: release
      name: "Documentation"
      if: branch = master AND type = push AND fork = false
      node_js: lts/*
      script: npm run build:docs
      deploy:
        provider: pages
        local_dir: build
        token: $GH_TOKEN
        skip_cleanup: true
        on:
          tags: false
